site_name: My Docs

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Reference:
    - Introduction: ref/introduction.md
    - PicoScope Common Functions: ref/common.md
    - PicoScope 6000 (A) Specific Functions: ref/ps6000a.md
    - PicoScope 5000 (A) Specific Functions: ref/ps5000a.md
  - Development: 
    - Current: dev/current.md
    - Roadmap: dev/roadmap.md


plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          allow_inspection: true
          docstring_style: numpy
          show_bases: true